import "./globals.scss";

import localFont from "next/font/local";
import Header from "../components/header/Hedaer";
import Footer from "../components/footer/Footer";

const fontDMsans = localFont({
    src: [
        {
            path: "./fonts/DMSans-Bold.woff2",
            weight: "700",
            style: "normal",
        },
        {
            path: "./fonts/DMSans-Medium.woff2",
            weight: "500",
            style: "normal",
        },
        {
            path: "./fonts/DMSans-Regular.woff2",
            weight: "400",
            style: "normal",
        },
    ],
    display: "swap",
});

const fontPoppins = localFont({
    src: [
        {
            path: "./fonts/Poppins-Bold.woff2",
            weight: "700",
            style: "normal",
        },
        {
            path: "./fonts/Poppins-Medium.woff2",
            weight: "500",
            style: "normal",
        },
        {
            path: "./fonts/Poppins-Regular.woff2",
            weight: "400",
            style: "normal",
        },
    ],
    display: "swap",
});

export const metadata = {
    title: "Portfolio",
    description: "Generated by create next app",
    icons: {
        icon: "/logo_freelancer.svg", // путь относительно папки public
        shortcut: "/logo_freelancer.svg",
        apple: "/logo_freelancer.svg",
        // other: {
        //   rel: 'apple-touch-icon-precomposed',
        //   url: '/apple-touch-icon-precomposed.png',
    },
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${fontDMsans.className} ${fontPoppins.className}`}
            >
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
